name: jane2
services:
- name: web
  environment_slug: python
  instance_size_slug: basic-xxs
  github:
    branch: main
    deploy_on_push: true
    repo: edstace/jane2
  run_command: |
    pip install flask-migrate
    export FLASK_APP=run.py
    flask db stamp head
    flask db upgrade
    gunicorn wsgi:app
  envs:
  - key: FLASK_APP
    scope: RUN_TIME
    value: run.py
  - key: FLASK_ENV
    scope: RUN_TIME
    value: production
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db.DATABASE_URL}
